name: "Setup Syft"
description: "Installs the Syft binary"
inputs:
  version:
    description: "Syft version to install."
    required: false
    default: "v1.42.1"
runs:
  using: "composite"
  steps:
    - name: Cache Syft binary
      id: cache-syft
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: /usr/local/bin/syft
        key: syft-${{ inputs.version }}-${{ runner.os }}

    - name: Setup Syft
      if: steps.cache-syft.outputs.cache-hit != 'true'
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin ${{ inputs.version }}
      shell: sh
