name: 'Setup Go'
description: 'Installs golang'
inputs:
  version:
    description: "Go version to install."
    required: false
    default: "1.24.1"
runs:
  using: "composite"
  steps:
    - name: Setup Golang
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
      with:
        go-version: ${{ inputs.version }}
