name: 'Setup Go'
description: 'Installs golang'
inputs:
  version:
    description: "Go version to install."
    required: false
    default: "1.22.5"
runs:
  using: "composite"
  steps:
    - name: Setup Golang
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
      with:
        go-version: ${{ inputs.version }}
