name: "Setup Go"
description: "Installs golang"
inputs:
  version:
    description: "Go version to install."
    required: false
    default: "1.26"
runs:
  using: "composite"
  steps:
    - name: Setup Golang
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
      with:
        go-version: ${{ inputs.version }}
