name: 'Setup Dotnet'
description: 'Installs dotnet core'
inputs:
  version:
    description: "Dotnet version to install."
    required: false
    default: "9.0.x"
runs:
  using: "composite"
  steps:
    - name: Setup Dotnet
      uses: actions/setup-dotnet@a66eefa2bf2572fc311ea6ff65a7b6ecc4df96a6
      with:
        dotnet-version: ${{ inputs.version }}
