name: Label Issues
on:
  issue_comment:
    types:
      - created
      - edited
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: label
        uses: ckotzbauer/label-command-action@05ccb82b1a9ee5c2b7a97b988bf8ed735362dcd9
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
