name: Label Issues
on:
  issue_comment:
    types:
      - created
      - edited
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f
      - name: label
        uses: ckotzbauer/label-command-action@ca5ca1788bae3f87a5963c366f7af4474e7ee49a
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
