name: Label issues

on:
  workflow_call:
    secrets:
      token:
        required: true

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  label-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - name: label
        uses: ckotzbauer/label-command-action@c2fd606b50ecf56f252cd97af4298d78502392ae
        env:
          GITHUB_TOKEN: "${{ secrets.token }}"
