name: Label issues

on:
  workflow_call:
    secrets:
      token:
        required: true

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  label-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
      - name: label
        uses: ckotzbauer/label-command-action@f9ff09d6cbe90ffe1d873deb66077718db470242
        env:
          GITHUB_TOKEN: "${{ secrets.token }}"
