name: Scan image

on:
  workflow_call:
    inputs:
      docker-tag:
        required: true
        type: string
      fail-on:
        required: false
        default: "medium"
        type: string
    secrets:
      ghcr-password:
        required: false

permissions:
  actions: read
  contents: read
  packages: read
  security-events: write
jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      GHCR_PASSWORD: ${{ secrets.ghcr-password }}
    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: GHCR Login
        if: ${{ env.GHCR_PASSWORD != '' }}
        run: docker login -u ${{ github.actor }} -p "$GHCR_PASSWORD" ghcr.io
        shell: sh

      - name: Scan image
        uses: ckotzbauer/actions-toolkit/grype@0.56.0 # 0.54.3
        with:
          scan-target: ${{ inputs.docker-tag }}
          fail-on: ${{ inputs.fail-on }}
          config-file: ".github/grype.yaml"
          format: "sarif"
          output: "results.sarif"
        continue-on-error: true

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
        with:
          sarif_file: results.sarif
          category: grype
