name: Lint

on:
  workflow_call:
    inputs:
      install-go:
        required: false
        default: false
        type: boolean
      go-version:
        required: false
        default: "1.26"
        type: string
      go-cache-dependency-path:
        description: "Path to Go dependency file(s) for cache key generation."
        required: false
        default: ""
        type: string
      install-node:
        required: false
        default: false
        type: boolean
      node-version:
        required: false
        default: 24
        type: string
      node-cache:
        description: "Node.js package manager for caching ('npm', 'yarn', 'pnpm'). Empty to disable."
        required: false
        default: "npm"
        type: string
      node-cache-dependency-path:
        description: "Path to Node.js dependency file(s) for cache key generation."
        required: false
        default: ""
        type: string
      lint-commands:
        required: true
        type: string

permissions:
  actions: read
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Setup Go
        if: ${{ inputs.install-go == true }}
        uses: ckotzbauer/actions-toolkit/setup-go@0.55.9 # 0.54.3
        with:
          version: ${{ inputs.go-version }}
          cache-dependency-path: ${{ inputs.go-cache-dependency-path }}

      - name: Setup Node
        if: ${{ inputs.install-node == true }}
        uses: ckotzbauer/actions-toolkit/setup-nodejs@0.55.9 # 0.54.3
        with:
          version: ${{ inputs.node-version }}
          cache: ${{ inputs.node-cache }}
          cache-dependency-path: ${{ inputs.node-cache-dependency-path }}

      - name: Lint
        run: ${{ inputs.lint-commands }}
